### PR TITLE
upload csv issue cannot read title fixed

### PR DESCRIPTION
**Pull request by mohit200008**
there was an issue where when you upload a csv file you get unable to read title that is fixed. Now when you upload csv file you get the certificate according to the category

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Hi Mohit,

The UI of the app needs full revamp so will be creating a figma design for it soon. Please revert the changes for the UI, We will be having new UI for the components.

**Comment by mohit200008** [comment]
> Hi Mohit,
> 
> The UI of the app needs full revamp so will be creating a figma design for it soon. Please revert the changes for the UI, We will be having new UI for the components.

**Comment by mohit200008** [comment]
should i again make the ui as it was and then make a PR because i actually commit all the changes at once??

**Comment by Abhishek-kumar09** [comment]
You can checkout to the master branch.
Pull the latest changes from the upstream/master
add your changes on top of it
make a commit.

**Pull request closed without merging**
